source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target "samixisa" do
     pod 'IQKeyboardManager'
     pod 'MBProgressHUD', '~> 0.9.2'
#    pod 'MJRefresh'
#	 pod 'CXDatePickerView'
end
